name: joss_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  accordion: ^2.6.0  
  connectivity_plus: ^6.0.2  
  collection: ^1.18.0
  const_date_time: ^1.1.0
  cupertino_icons: ^1.0.8  
  date_field: ^6.0.0
  dropdown_search: ^6.0.1  
  equatable: ^2.0.3
  flex_color_scheme: ^8.0.2
  file_picker: ^8.0.0+1
  flutter_animate: ^3.0.0     
  flutter_bloc: ^9.1.1
  flutter_slidable: ^3.1.2
  flutter_staggered_animations: ^1.1.1 
  flutter_svg: ^2.0.17   
  foundation: ^0.0.5
  google_sign_in: ^6.3.0    
  google_sign_in_web: ^0.12.4+4
  google_fonts: ^6.1.0   
  grouped_list: ^6.0.0
  http: ^1.2.1
  image: any
  image_picker: ^1.0.7
  intl: ^0.19.0
  js: ^0.6.7
  jwt_decoder: ^2.0.1
  mime: ^2.0.0
  meta: ^1.10.0  
  path: ^1.9.0
  path_provider: ^2.0.11
  quick_input_formatters: ^0.0.4
  shared_preferences: ^2.5.3
  string_validator: ^1.0.2  
  timelines_plus: ^1.0.3
  uuid: ^4.5.1
  mobile_chat_flutter: ^1.0.2
  hydrated_bloc: ^10.1.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:  
    - assets/images/
    - assets/images/month/
    - assets/icons/
    - assets/images/jps-image.png
    - assets/images/vector-1.png
    - assets/images/vector-2.png
    - assets/images/vector-3.png
    - assets/images/vector-4.png
    - assets/images/vector-5.png
    - assets/images/vector-6.png
    - assets/images/vector-7.png
    - assets/images/vector-8.png
    - assets/images/vector-9.png
    - assets/images/vector-10.png
    - assets/images/vector-11.png
    - assets/images/shape-bottom.svg
    - assets/images/vector-home.png
    - assets/images/vector-12.png
    - assets/images/vector-13.png
    - assets/images/vector-14.png
    - assets/images/vector-15.png
    - assets/images/background_gradient.png
    - assets/icons/jps_logo.svg
    - assets/icons/notification.png
    - assets/icons/logo_jps_no_background.png
    - assets/icons/cari-asuransi-1.svg
    - assets/icons/lapor-klaim-2.svg
    - assets/icons/aset-3.svg
    - assets/icons/polis-4.svg
    - assets/icons/beli-polis-5.svg
    - assets/icons/klaim-6.svg
    - assets/icons/tagihan-pembayaran-7.svg
    - assets/images/start-1.svg
    - assets/images/start-2.svg
    - assets/images/start-3.svg

  fonts:
    - family: Delm-Regular
      fonts:
        - asset: assets/fonts/Delm-Regular.ttf
          weight: 400
    - family: Delm
      fonts:
        - asset: assets/fonts/Delm-Thin.ttf
          weight: 100
        - asset: assets/fonts/Delm-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Delm-Light.ttf
          weight: 300
        - asset: assets/fonts/Delm-Regular.ttf
          weight: 400
        - asset: assets/fonts/Delm-Medium.ttf
          weight: 500
        - asset: assets/fonts/Delm-Bold.ttf
          weight: 700
        - asset: assets/fonts/Delm-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Delm-Black.ttf
          weight: 900
